"""A vetted, hand-written library of short educational tips.

These are deliberately NOT generated by an AI at runtime, so nothing incorrect
or misleading can slip into a published post. Add your own below. One tip is
picked per day, rotating deterministically by date so it never repeats two days
in a row and cycles through the whole list."""
from datetime import date
from typing import Tuple

TIPS = [
    ("The power of SIPs",
     "A Systematic Investment Plan invests a fixed amount on a schedule. It "
     "removes timing guesswork and uses rupee-cost averaging — you buy more "
     "units when prices are low, fewer when high."),
    ("What is an index?",
     "An index like Nifty 50 tracks a basket of large companies. It's a "
     "snapshot of the broad market, not a single stock — a useful benchmark "
     "for how 'the market' is doing."),
    ("Diversification",
     "Don't put everything in one stock or sector. Spreading investments "
     "reduces the impact if any single holding falls sharply."),
    ("Emergency fund first",
     "Before investing in markets, keep 3–6 months of expenses in a safe, "
     "liquid place. It stops you from selling investments at a bad time."),
    ("Compounding",
     "Returns earning their own returns is how small, consistent investments "
     "grow large over decades. Time in the market matters more than timing it."),
    ("Expense ratios matter",
     "For mutual funds and ETFs, the annual fee (expense ratio) quietly eats "
     "returns over time. Lower-cost funds keep more money working for you."),
    ("P/E ratio, simply",
     "Price-to-Earnings compares a stock's price to its profit per share. A "
     "high P/E can mean high growth expectations — or that it's expensive."),
    ("Large vs mid vs small cap",
     "Large-caps are generally more stable; mid and small-caps can grow faster "
     "but swing harder. Your mix should match your risk comfort and horizon."),
    ("Don't chase tips",
     "A stock that rose 20% today isn't automatically a buy. Understand the "
     "business and valuation before acting on hype."),
    ("Asset allocation",
     "How you split money across equity, debt, and gold usually drives returns "
     "more than which exact stock you pick. Review it periodically."),
    ("Market volatility is normal",
     "Indices routinely rise and fall. Short-term dips are not the same as "
     "permanent loss — reacting emotionally is where investors lose most."),
    ("Know your goal & horizon",
     "Money you need in 1 year should not be in volatile equities. Match the "
     "investment's risk to when you'll actually need the cash."),
]


def tip_for_today() -> Tuple[str, str]:
    """Deterministically pick a tip by day-of-year so runs are reproducible."""
    idx = date.today().timetuple().tm_yday % len(TIPS)
    return TIPS[idx]
